config/routes.rb
Rails.application.routes.draw do

  root to:'welcome#main'

  get '/main'  => 'welcome#main'
  get '/sobreNosotros'  => 'welcome#sobreNosotros'
  get '/testimonios'  => 'welcome#testimonios'
  get '/contact'  => 'welcome#contact'
  get '/noticias'  => 'welcome#noticias'
  get '/login'  => 'welcome#login'
  get '/registro'  => 'welcome#registro'
  get '/regcliente' => 'welcome#regcliente'
  get '/regestilista' => 'welcome#regestilista'

  get '/mainC'  => 'clientes#mainC'
  get '/perfil' => 'clientes#perfil'
  patch '/perfil' => 'clientes#editarcliente'

  get '/misCitas' => 'clientes#misCitas'
  post '/listaCitas' => 'clientes#listaCitas'
  post '/crearcita' => 'clientes#crearcita'

  get 'citasProgramadas' => 'clientes#citasProgramadas'
  get '/puntosCercanos' => 'clientes#puntosCercanos'
  get '/estilistas' => 'clientes#estilistas'
  get '/experiencias' => 'clientes#experiencias'
  post '/experiencias' => 'clientes#nuevaexperiencia'

  get '/mainest' => 'estilistas#mainest'
  get '/perfilest' => 'estilistas#perfilest'
  patch '/perfilest' => 'estilistas#editarestilista'

  get '/cortesest' => 'estilistas#cortesest'
  post '/cortesest' => 'estilistas#agregarcorte'

  get '/citaspest' => 'estilistas#citaspest'
  post '/confirmarcita' => 'estilistas#confirmarcita'

  get '/agendaest' => 'estilistas#agendaest'
  post '/agendaest/guardar' => 'estilistas#agendaestnew'
  get '/horarios' => 'estilistas#horarios'

  get '/verexpest' => 'estilistas#verexpest'
  post '/verexpest' => 'estilistas#nuevaverexpest'

  post '/entrar' => 'welcome#entrar'

  post '/registrarme' => 'welcome#registrarme'
  post '/regclientes' => 'welcome#regclientes'
  post '/regestilistas' => 'welcome#regestilistas'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def main
    session.delete(:persona_id)
  end

  def contact
  end

  def login
  end

  def noticias
  end

  def registro
  end

  def sobreNosotros
  end

  def testimonios
  end

  def entrar
    parametros_seguros = entrar_params
    cedula = parametros_seguros[:cedula]
    nombre = parametros_seguros[:nombre]

    if persona = Person.find_by(cedula: cedula) and persona.tipo == "Cliente" and persona.nombre == nombre
      session[:persona_id] = persona.id
      redirect_to controller: 'clientes', action: 'mainC'
    elsif persona = Person.find_by(cedula: cedula) and persona.tipo == "Estilista" and persona.nombre == nombre
      session[:persona_id] = persona.id
      redirect_to controller: 'estilistas', action: 'mainest'
    else 
      flash[:notice] = "Datos incorrectos"
      redirect_to login_path
    end
  end


  def registrarme
  end

  def regclientes

    person = Person.new
    datos = regcliente_params

    person.nombre = datos[:nombre]
    person.apellido = datos[:apellido]
    person.cedula = datos[:cedula]
    person.fecha_nacimiento = datos[:nacimiento]
    person.genero = datos[:genero]
    person.telefono_movil = datos[:movil]
    person.telefono_fijo = datos[:fijo]
    person.tipo = "Cliente"
    person.ubication_id = 1

    person.save

    cliente = Customer.new
    cliente.person_id = person.id
    cliente.tipo_discapacidad =datos[:tipo] 

    if cliente.save
      flash[:notice] = "Su registro ha sido exitoso"
      redirect_to regcliente_path
    end
  
  end

  def regestilistas

    person = Person.new
    datos = regestilista_params

    person.nombre = datos[:nombre]
    person.apellido = datos[:apellido]
    person.cedula = datos[:cedula]
    person.fecha_nacimiento = datos[:nacimiento]
    person.genero = datos[:genero]
    person.telefono_movil = datos[:movil]
    person.telefono_fijo = datos[:fijo]
    person.tipo = "Estilista"
    person.ubication_id = 1

    person.save

    estilista = Stylist.new
    estilista.person_id = person.id
    estilista.especialidad = datos[:especialidad]
    estilista.correo_electronico = datos[:correo] 

    if estilista.save
      flash[:notice] = "Su registro ha sido exitoso"
      redirect_to regestilista_path
    end
  end


  private

  def entrar_params
   params.permit(:cedula,:nombre)
 end

 def regcliente_params
   params.permit(:nombre, :apellido, :cedula, :nacimiento, :genero, :movil, :fijo, :tipo)
 end

 def regestilista_params
   params.permit(:nombre, :apellido, :cedula, :especialidad, :nacimiento, :genero, :movil, :fijo, :tipo, :correo)
 end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/contact.html.erb
<link rel="stylesheet" type="text/css" href="../css/botones.css">
<link rel="stylesheet" type="text/css" href="../css/welcome/contact.css">
<link rel="stylesheet" href="css/voz.css">
<script type="text/javascript" src="scripts/voz.js"></script>
<script type="text/javascript" src="scripts/alertas.js"></script>
<h1 align="center">¡Únete!</h1>
<h4 align="center">Si quieres ser un Estilista de Corazón envía tus datos.</h4>
<div class="form-style-9">
	<ul>
		<li>
			<input id="inputContacto0" type="text" name="nombre" class="field-style field-split align-left" placeholder="Nombre" onclick="procesar(0)"/>
			<input id="inputContacto1" type="text" name="celular" class="field-style field-split align-right" placeholder="Celular" onclick="procesar(1)"/>

		</li>
		<li>
			<input id="inputContacto2" type="text" name="correo_electronico" class="field-style field-split align-left" placeholder="Correo electrónico" onclick="procesar(2)"/>
			<input id="inputContacto3" type="text" name="sitio_web" class="field-style field-split align-right" placeholder="Sitio web" onclick="procesar(3)"/>
		</li>
		<li>
			<input id="inputContacto4" type="text" name="asunto" class="field-style field-full align-none" placeholder="Asunto" onclick="procesar(4)"/>
		</li>
		<li>
			<textarea type="text" id="inputContacto5" name="mensaje" class="field-style" placeholder="Mensaje" onclick="procesar(5)"></textarea>
		</li>
	</ul>
	<div style="padding-left: 42%;" class="boton"><button type="button" class="btn btn-primary" onclick="alertas(4)">Enviar</button></div>
</div >

app/views/welcome/login.html.erb
<link rel="stylesheet" type="text/css" href="css/botones.css"/>
<link rel="stylesheet" type="text/css" href="css/welcome/login.css"/>
<link rel="stylesheet" type="text/css" href="css/alerta.css"/>


<h1 align="center">¡Ingresa!</h1>
<h4 align="center">Observa las novedades.</h4>
<%= form_tag '/entrar', class: 'form-style-9' do %>
<% if flash[:notice] %>

	<div class="alert alert-danger alert-dismissable">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
    <strong><%= flash[:notice] %> </strong>
    </div>

<% end %>

<ul>
	<label for="Cedula">Identificación</label>
	<li>
		<input type="text" id="cedula" name="cedula" class="field-style field-full align-none" placeholder="Identificación" required/>
	</li>
	<label for="Nombre">Nombre</label>
	<li>
		<input type="text" id="nombre" name="nombre" class="field-style field-full align-none" placeholder="Nombre" />
	</li>
	<li>
		<br>
		<div style="padding-left: 23%;" class="offset-sm-2 col-sm-10">
		<%= link_to "Registrarse", registro_path, :class => "btn btn-primary" %>
		<button type="submit" value="Entrar" class="btn btn-primary">Entrar</button>
		</div>
	</li>
</ul>
<% end %>	

app/views/welcome/main.html.erb
<script src="scripts/slider.js"></script>
<br>
<div id="myCarousel" class="carousel slide" data-ride="carousel"> 
  <!-- Indicators -->
  
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active"> <img src="images/sl1.jpg" style="width:100%" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Únete a esta iniciativa.</h1>
        </div>
      </div>
    </div>
    <div class="item"> <img src="images/sl2.jpg" style="width:100%" data-src="" alt="Second    slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Cambia la manera de ofrecer tus servicios.</h1>
        </div>
      </div>
    </div>
    <div class="item"> <img src="images/sl3.jpg" style="width:100%" data-src="" alt="Third slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Nuestros profesionales te consentirán.</h1>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a> </div>

app/views/welcome/noticias.html.erb
<style>
img {
  border: 0;
}
img {
    page-break-inside: avoid;
  }
  img {
    max-width: 100% !important;
  }
  img {
  vertical-align: middle;
}
.img-responsive,
.thumbnail > img,
.thumbnail a > img,
.carousel-inner > .item > img,
.carousel-inner > .item > a > img {
  display: block;
  max-width: 100%;
  height: auto;
}
.img-rounded {
  border-radius: 6px;
}
.img-thumbnail {
  display: inline-block;
  max-width: 100%;
  height: auto;
  padding: 4px;
  line-height: 1.42857143;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 4px;
  -webkit-transition: all .2s ease-in-out;
       -o-transition: all .2s ease-in-out;
          transition: all .2s ease-in-out;
}
.img-circle {
  border-radius: 50%;
}
h4{
  width: 90%;
  text-align: left;
}
</style> 
<h1 align="center">Paralímpicos que ven con la mente</h1>
<div align="center">
<h4>	
Uno de los rincones más interesantes de una Olimpiada de ajedrez es el de los ciegos, que juegan en tableros distintos. Es el deporte más igualitario y el ideal para ellos, ya sean de nacimiento o sobrevenidos. Algunos llegan a un alto nivel y forman la selección mundial que estos días compite en Bakú (Azerbaiyán), donde también hay equipos de discapacitados y sordos.
</h4>
<div align="center"><img class="img-responsive" src="images/noticia1.jpg" width="730" height="460"></div>
<text align="center"><i>Cortesía Periódico El Tiempo.</i></h4><br></div>

<h1 align="center">800 kilómetros de senderos en silla de ruedas</h1>
<div align="center">
<h4>	
Un joven con parálisis cerebral hace el Camino de Santiago francés para promover la accesibilidad.
</h4>
<div align="center"><img class="img-responsive" src="images/noticia2.jpg" width="730" height="420"></div>
<text align="center"><i>Cortesía Periódico El Tiempo.</i></h4></div><br>

app/views/welcome/regcliente.html.erb
<link rel="stylesheet" type="text/css" href="../css/botones.css">
<link rel="stylesheet" type="text/css" href="../css/welcome/contact.css">
<link rel="stylesheet" href="css/voz.css">
<link rel="stylesheet" type="text/css" href="css/alerta.css"/>

<script type="text/javascript" src="scripts/voz.js"></script>
<%= form_tag '/regclientes', class: 'form-style-9' do %>
<% if flash[:notice] %>
<div class="alert alert-success alert-dismissable" >
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <strong><%= flash[:notice] %> </strong>
</div>
<% end %>

<ul>
  <label for="Cedula">Cédula</label>
  <li>
    <input type="text" id="inputRegCliente24" name="cedula" class="field-style field-full align-none" placeholder="Introduce tu número de identificación" onclick="procesar(24)"/>
  </li>
  <label for="Nombre">Nombre</label>
  <li>
    <input type="text" id="inputRegCliente25" name="nombre" class="field-style field-full align-none" placeholder="Introduce tu nombre" required onclick="procesar(25)"/>
  </li>
  <label for="Apellido">Apellido</label>
  <li>
    <input type="text" id="inputRegCliente26" name="apellido" class="field-style field-full align-none" placeholder="Introduce tu apellido" onclick="procesar(26)"/>
  </li>
  <label for="Tipo">Tipo de discapacidad</label>
  <li>
    <select id="tipo" name="tipo" class="field-style field-full align-none">
      <option value=""></option>
      <option value="Fisica">Física</option>
      <option value="Psicosocial">Psicosocial</option>
      <option value="Cognitiva">Cognitiva</option>
      <option value="Sensorial">Sensorial</option>
    </select>
  </li>
  <label for="Nacimiento">Fecha de nacimiento</label>
  <li>
    <input type="date" id="nacimiento" name="nacimiento" class="field-style field-full align-none" placeholder="Selecciona tu fecha de nacimiento" />
  </li>
  <label for="Fijo">Teléfono fijo</label>
  <li>
    <input type="text" id="inputRegCliente30" name="fijo" class="field-style field-full align-none" placeholder="Introduce tu número fijo" onclick="procesar(30)"/>
  </li>
  <label for="Movil">Teléfono móvil</label>
  <li>
    <input type="text" id="movil" name="movil" class="field-style field-full align-none" placeholder="Introduce tu número móvil" />
  </li>
  <li>
    <br>
    <div align="center"><button type="submit" class="btn btn-primary">Enviar</button></div>
  </li>
</ul>
<% end %>

app/views/welcome/regestilista.html.erb
<link rel="stylesheet" type="text/css" href="../css/welcome/contact.css">
<link rel="stylesheet" type="text/css" href="../css/botones.css">
<link rel="stylesheet" type="text/css" href="css/alerta.css"/>

<%= form_tag '/regestilistas', class: 'form-style-9' do %>

<% if flash[:notice] %>
<div class="alert alert-success alert-dismissable" >
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <strong><%= flash[:notice] %> </strong>
</div>
<% end %>


<ul>
  <label for="Cedula">Cédula</label>
  <li>
    <input type="text" id="cedula" name="cedula" class="field-style field-full align-none" placeholder="Introduce tu número de identificación" />
  </li>
  <label for="Nombre">Nombre</label>
  <li>
    <input type="text" id="nombre" name="nombre" class="field-style field-full align-none" placeholder="Introduce tu nombre" required/>
  </li>
  <label for="Apellido">Apellido</label>
  <li>
    <input type="text" id="apellido" name="apellido" class="field-style field-full align-none" placeholder="Introduce tu apellido" />
  </li>
  <label for="Especialidad">Especialidad</label>
  <li>
    <select id="especialidad" name="especialidad" class="field-style field-full align-none">
      <option value=""></option>
      <option value="Barberia">Barbería</option>
      <option value="Peluqueria">Peluquería</option>
    </select>
  </li>
  <label for="Nacimiento">Fecha de nacimiento</label>
  <li>
    <input type="date" id="nacimiento" name="nacimiento" class="field-style field-full align-none" placeholder="Selecciona tu fecha de nacimiento" />
  </li>
  <label for="Fijo">Teléfono fijo</label>
  <li>
    <input type="text" id="fijo" name="fijo" class="field-style field-full align-none" placeholder="Introduce tu número fijo" />
  </li>
  <label for="Movil">Teléfono móvil</label>
  <li>
    <input type="text" id="movil" name="movil" class="field-style field-full align-none" placeholder="Introduce tu número móvil" />
  </li>
  <label for="Correo">Correo electrónico</label>
  <li>
    <input type="email" id="correo" name="correo" class="field-style field-full align-none" placeholder="Introduce tu correo electrónico" />
  </li>
  <li>
    <br>
    <div align="center"><button type="submit" class="btn btn-primary">Enviar</button></div>
  </li>
</ul>

<% end %>

app/views/welcome/registro.html.erb
<link rel="stylesheet" type="text/css" href="../css/botones.css">
<div align="center">
	<h1>¿Eres un nuevo cliente o un estilista? </h1>
	<br><br>
	<%= link_to "Cliente", regcliente_path, :class => "btn btn-primary btn-lg active"  %>
	<%= link_to "Estilista", regestilista_path, :class => "btn btn-default btn-lg active" %>
</div>

<br>
<br>
<br>
<br>
<br>

app/views/welcome/sobreNosotros.html.erb
<link rel="stylesheet" type="text/css" href="../css/welcome/sobreNosotros.css">
<style>
.about{
	width: 85%;
	text-align: left;
}
</style>
<div align="center">
<div class="about">
<div id="container">
<div id="contenidom"><img src="images/mision.png" width="150" height="200"></div>
<h1 align="center">Misión</h1>
</div>
<h4>Reunir estilistas profesionales en Medellín que estén dispuestos a brindar servicios de belleza integral (corte, manicure, pedicure, entre otros) y una atención personalizada a personas discapacitadas (con baja visión y/o movilidad reducida) y de la tercera edad con el fin de que ellos puedan sentirse participantes activos de la sociedad y contribuir a su imagen personal.</h4><br><br><br><br><br>

<div align="center" id="container">
<div id="contenidovi"><img src="images/vision.png" width="250" height="240"></div>
<h1 align="center">Visión</h1>
</div>
<h4>Ser una organización reconocida en todo Colombia y ofrecer nuestros servicios en las principales ciudades del país, entre las cuales se encuentran Bogotá y Cali. También, en un año, se pretende llegar a ser más conocidos a través de las redes sociales para de esta forma convocar aún más estilistas que puedan hacer parte de esta iniciativa.</h4><br><br><br><br><br><br>

<div id="container">
<div id="contenidov"><img src="images/valores.png" width="150" height="220"></div>
<h1 align="center">Valores</h1>
<h4>Nuestros profesionales se caracterizan por poseer y fortalecer en su labor diaria los siguientes valores:</h4>
<ul>
<li><h4>Respeto.</h4></li>
<li><h4>Tolerancia.</h4></li>
<li><h4>Paciencia.</h4></li>
<li><h4>Vocación.</h4></li>
<li><h4>Compromiso.</h4></li>
</ul>
</div>
</div>
</div>

app/views/welcome/testimonios.html.erb
<style>
img {
  border: 0;
}
img {
    page-break-inside: avoid;
  }
  img {
    max-width: 100% !important;
  }
  img {
  vertical-align: middle;
}
.img-responsive,
.thumbnail > img,
.thumbnail a > img,
.carousel-inner > .item > img,
.carousel-inner > .item > a > img {
  display: block;
  max-width: 100%;
  height: auto;
}
.img-rounded {
  border-radius: 6px;
}
.img-thumbnail {
  display: inline-block;
  max-width: 100%;
  height: auto;
  padding: 4px;
  line-height: 1.42857143;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 4px;
  -webkit-transition: all .2s ease-in-out;
       -o-transition: all .2s ease-in-out;
          transition: all .2s ease-in-out;
}
.img-circle {
  border-radius: 50%;
}
</style>
<div align="center">
<div style="width: 85%; text-align: left;" class="testimonio">
<br>
<div class="container">
<div align="center"><img src="images/persona1.jpg" class="img-responsive" alt="Responsive image">
<h1 align="center">Andrés Ceballos</h1>
</div>
<h4>Hace poco me enteré de esta bella iniciativa y ahora soy miembro activo de ella. Me emociona cuando llego a la casa de un cliente y me recibe con una gran sonrisa, es una hermosa labor la que nosotros como estilistas podemos desempeñar, espero que cada día seamos más los que nos unamos por esta bonita causa.</h4><br><br></div>

<div class="container">
<div align="center"><img src="images/persona2.jpg" class="img-responsive" width="680">
<h1 align="center">Nora Acevedo</h1>
</div>
<h4>Mis hijos no podían llevarme a la peluquería muy seguido, así que debía esperar mucho tiempo para poder arreglarme el cabello. Desde que soy parte de Estilistas de Corazón no tengo que esperar un mes para hacerme mi corte de cabello, puedo ingresar a la página fácilmente y agendar una cita con mi estilista preferido, o intentar algo nuevo mirando el catálogo de otros profesionales. ¡Es lo mejor!</h4><br>
</div>