config/routes.rb
Rails.application.routes.draw do

  root to:'welcome#main'

  get '/main'  => 'welcome#main'
  get '/sobreNosotros'  => 'welcome#sobreNosotros'
  get '/testimonios'  => 'welcome#testimonios'
  get '/contact'  => 'welcome#contact'
  get '/noticias'  => 'welcome#noticias'
  get '/login'  => 'welcome#login'
  get '/registro'  => 'welcome#registro'
  get '/regcliente' => 'welcome#regcliente'
  get '/regestilista' => 'welcome#regestilista'

  get '/mainC'  => 'clientes#mainC'
  get '/perfil' => 'clientes#perfil'
  patch '/perfil' => 'clientes#editarcliente'

  get '/misCitas' => 'clientes#misCitas'
  post '/listaCitas' => 'clientes#listaCitas'
  post '/crearcita' => 'clientes#crearcita'

  get 'citasProgramadas' => 'clientes#citasProgramadas'
  get '/puntosCercanos' => 'clientes#puntosCercanos'
  get '/estilistas' => 'clientes#estilistas'
  get '/experiencias' => 'clientes#experiencias'
  post '/experiencias' => 'clientes#nuevaexperiencia'

  get '/mainest' => 'estilistas#mainest'
  get '/perfilest' => 'estilistas#perfilest'
  patch '/perfilest' => 'estilistas#editarestilista'

  get '/cortesest' => 'estilistas#cortesest'
  post '/cortesest' => 'estilistas#agregarcorte'

  get '/citaspest' => 'estilistas#citaspest'
  post '/confirmarcita' => 'estilistas#confirmarcita'

  get '/agendaest' => 'estilistas#agendaest'
  post '/agendaest/guardar' => 'estilistas#agendaestnew'
  get '/horarios' => 'estilistas#horarios'

  get '/verexpest' => 'estilistas#verexpest'
  post '/verexpest' => 'estilistas#nuevaverexpest'

  post '/entrar' => 'welcome#entrar'

  post '/registrarme' => 'welcome#registrarme'
  post '/regclientes' => 'welcome#regclientes'
  post '/regestilistas' => 'welcome#regestilistas'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/estilistas_controller.rb
class EstilistasController < ApplicationController

	def mainest
		if autorizado("Estilista")
		end
		id_estilista = session[:persona_id]

		persona = Person.find_by(id: id_estilista)

		@nombre = persona.nombre

		id_estilista = Stylist.find_by(person_id: session[:persona_id]).id

		@citassol = Appointment.where(stylist_id: id_estilista , estado: 0)
	end

	def agendaest
		if autorizado("Estilista")
		end
	end

	def agendaestnew
		if autorizado("Estilista")
		end
		datos = params.permit(:fecha,:horain,:horafin,:lapso)

		inicial= datos[:horain].to_time.hour* 60 + datos[:horain].to_time.min
		final= datos[:horafin].to_time.hour* 60 + datos[:horafin].to_time.min
		lapso= datos[:lapso].to_time.hour* 60 + datos[:lapso].to_time.min

		var = (final - inicial) / lapso

		horainicio = inicial
		id_est = session[:persona_id]

		estilista = Stylist.find_by(person_id: id_est)

		for i in 0..var-1
			horario = Schedule.new

			horario.fecha = datos[:fecha]
			horario.hora_inicio = ((inicial/60).to_s + ":" + (inicial%60).to_s ).to_time
			inicial+= lapso
			horario.hora_fin = ((inicial/60).to_s + ":" + (inicial%60).to_s ).to_time
			horario.stylist_id = estilista.id

			if horario.save
                        	flash[:notice] = "Horario agregado exitosamente"
                        	#redirect_to agendaest_path
                        end
		end
	end

	def citaspest
		if autorizado("Estilista")
		end 

		id_estilista = Stylist.find_by(person_id: session[:persona_id]).id 
		@citasp = Appointment.where(stylist_id: id_estilista , estado: 0)
	end

	def confirmarcita
		if autorizado("Estilista")
		end


		cita = Appointment.find_by(id: confirmarcita_params[:id])

		puts cita.hora_inicio

		if confirmarcita_params[:confirmar]== "1"
			cita.estado=1

		end

		if confirmarcita_params[:cancelar]== "2"
			cita.estado=2
		end

		if cita.save
			redirect_to citaspest_path
		end
	end

	def cortesest
		if autorizado("Estilista")
		end
		@haircut = Haircut.new
		@cortes = Haircut.all.order("created_at ASC")	
		@cut = Haircut.all.order("created_at ASC")	
	end

	def agregarcorte
		if autorizado("Estilista")
		end
		corte = Haircut.new agregarcorte_params

		if corte.save
			id_estilista = session[:persona_id]
			estilista = Stylist.find_by(person_id: id_estilista)
			corte = Haircut.find_by(id: corte.id)
			cortest = HaircutStylist.new
			cortest.stylist_id = estilista.id
			cortest.haircut_id = corte.id
			cortest.save
			redirect_to cortesest_path
		end
	end

	def perfilest
		if autorizado("Estilista")
		end

		id_estilista = session[:persona_id]

		@persona = Person.find_by(id: id_estilista)
		@estilista = Stylist.find_by(person_id: id_estilista)
		@ubicacion = Ubication.find_by(id: @persona.ubication_id)
	end

	def editarestilista
		if autorizado("Estilista")
		end


		datos = updateestilista_params


		id_estilista = session[:persona_id]

		ubicacion = Ubication.new
		ubicacion.direccion = updateestilistau_params[:direccion]
		ubicacion.barrio = updateestilistau_params[:barrio]

		if ubicacion.save
			persona = Person.find_by(id: id_estilista) 
			persona.nombre = datos[:nombre]
			persona.apellido = datos[:apellido]
			persona.fecha_nacimiento = datos[:fecha_nacimiento]
			persona.telefono_movil = datos[:telefono_movil]
			persona.telefono_fijo = datos[:telefono_fijo]
			persona.foto_perfil = datos[:foto_perfil]
			persona.ubication_id = ubicacion.id

			estilista = Stylist.find_by(person_id: id_estilista)
			estilista.correo_electronico = updateestilistad_params[:correo_electronico]

			if estilista.save and persona.save
				flash[:notice] = "Se actualizaron los datos con éxito"
				redirect_to perfilest_path
			end
		end

	end 

	def verexpest
		if autorizado("Estilista")
		end

		@experience = Experience.new
		@experiencias = Experience.all.order("created_at ASC")
		@experienciasm = Experience.all.order("created_at ASC")
	end

	def nuevaverexpest
		if autorizado("Estilista")
		end

		experiencia = Experience.new nuevaexperiencia_params
		experiencia.person_id = session[:persona_id]

		if experiencia.save
			redirect_to verexpest_path
		end

	end

	def horarios
		if autorizado("Estilista")
		end
		@schedules = Schedule.all.order("created_at ASC")
	end

	private

	def updateestilista_params
		params.require(:person).permit(:nombre, :apellido, :fecha_nacimiento, :telefono_movil, :telefono_fijo, :foto_perfil)
	end

	def updateestilistad_params
		params.require(:stylist).permit(:correo_electronico)
	end

	def updateestilistau_params
		params.require(:ubication).permit(:barrio, :direccion)
	end

	def nuevaexperiencia_params
		params.require(:experience).permit(:comentario,:foto_exp)
	end

	def agregarcorte_params
		params.require(:haircut).permit(:nombre_corte,:descripcion,:foto)
	end

	def confirmarcita_params
		params.permit(:confirmar,:cancelar,:id)
	end	

	def corte_params
		params.permit(:id)
	end
end

app/views/estilistas/_cut.html.erb
<%= form_for @haircut, :url => cortesest_path, html: { multipart: true } do |f| %>
<div class="modal-body">
  <div align="center">
    <div class="contenido">
      <div class="form_group row">
        <%= f.label :nombre, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">  
          <%= f.text_field :nombre_corte, class: "form-control", :required => true %>
        </div>
      </div>
      <br>
      <div class="form_group row">
        <%= f.label :detalles, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10"> 
        <%= f.text_area :descripcion, class: "form-control" %>
        </div>
      </div>
      <br>
      <div class="form_group row">
        <%= f.label :foto, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10"> 
        <%= f.file_field :foto, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal-footer">
  <%= f.submit "Agregar corte",class: "btn btn-primary" %>
  <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
</div>
<% end %>

app/views/estilistas/_expe.html.erb
<%= form_for @experience, :url => verexpest_path, html: { multipart: true } do |f| %>
<div class="modal-body">
  <div align="center">
    <div class="contenido">
      <div class="form_group row">
        <%= f.label :relato, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">  
          <%= f.text_area :comentario, class: "form-control", :required => true %>
        </div>
      </div>
      <br>
      <div class="form_group row">
        <%= f.label :foto, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10"> 
        <%= f.file_field :foto_exp, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal-footer">
  <%= f.submit "Registrar experiencia",class: "btn btn-primary" %>
  <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
</div>
<% end %>

app/views/estilistas/_perfilform.html.erb
<%= form_for @persona, :url => perfilest_path, html: { multipart: true } do |f| %>
<%= form_for @estilista, :url => perfilest_path, html: { multipart: true } do |j| %>
<%= form_for @ubicacion, :url => perfilest_path, html: { multipart: true } do |i| %>

<% if @persona.foto_perfil_file_name %>
<div align="center"><img src="<%= @persona.foto_perfil %>" width="150" height="145"></div><br>
<% end %>

<div align="center">
	<div class="container">

		<div class="form-group row">
			<%= f.label :nombre, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">  
				<%= f.text_field :nombre, class: "form-control", :required => true%>
			</div>
		</div>

		<div class="form-group row">
			<%= f.label :apellido, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">  
				<%= f.text_field :apellido, class: "form-control", :required => true%>
			</div>
		</div>

		<div class="form-group row">
			<%= f.label :fecha_nacimiento, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">  
				<%= f.date_field :fecha_nacimiento, class: "form-control", :required => true %>
			</div>
		</div>

		<div class="form-group row">
			<%= f.label :teléfono_fijo, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">  
				<%= f.text_field :telefono_fijo, class: "form-control", :required => true%>
			</div>
		</div>

		<div class="form-group row">
			<%= f.label :teléfono_movil, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">  
				<%= f.text_field :telefono_movil, class: "form-control", :required => true%>
			</div>
		</div>

		<div class="form-group row">
			<%= j.label :correo, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">  
				<%= j.text_field :correo_electronico, class: "form-control", :required => true%>
			</div>
		</div>

		<div class="form-group row">
			<%= i.label :local, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">  
				<%= i.text_field :barrio, class: "form-control", :required => true, id:"inputPerfilCliente15"%>
			</div>
		</div>

		<div class="form-group row">
			<%= i.label :dirección, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">  
				<%= i.text_field :direccion, class: "form-control", :required => true%>
			</div>
		</div>

		<div class="form_group row">
			<%= f.label :foto_perfil, class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10"> 
				<%= f.file_field :foto_perfil, class: "form-control" %>
			</div>
		</div>
		<br>
		<div class="form-group row">
			<div style="padding-left: 48%;" class="offset-sm-2 col-sm-10">
				<button type="submit" class="btn btn-primary">Editar</button>
			</div>
		</div>
	</div>
</div>


<% end %>
<% end %>
<% end %>

app/views/estilistas/agendaest.html.erb
<link rel="stylesheet" type="text/css" href="css/estilistas.css">
<link rel="stylesheet" type="text/css" href="css/alerta.css"/>
<br>
<h1 align="center">Agenda</h1><br>
<div align="center">
  <div class="container1">
    <%= form_tag '/agendaest/guardar', class: 'form-style-9' do %>
    <% if flash[:notice] %>

        <div class="alert alert-danger alert-dismissable">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
    <strong><%= flash[:notice] %> </strong>
    </div>

<% end %>

    <div class="form-group row">
      <label for="fecha" class="col-sm-2 col-form-label">Fecha</label>
      <div class="col-sm-10">
        <input type="date" class="form-control" name="fecha" id="fecha" placeholder="Introduce la fecha">
      </div>
    </div>
    <div class="form-group row">
      <label for="horain" class="col-sm-2 col-form-label">Hora inicio</label>
      <div class="col-sm-10">
        <input type="time" class="form-control" name="horain" id="horain" placeholder="Introduce la hora de inicio de tu día" required> 
      </div>
    </div>
    <div class="form-group row">
      <label for="horafin" class="col-sm-2 col-form-label">Hora fin</label>
      <div class="col-sm-10">
        <input type="time" class="form-control" name="horafin" id="horafin" placeholder="Introduce la hora en que finaliza tu día"> 
      </div>
    </div>
    <div class="form-group row">
      <label for="hasta" class="col-sm-2 col-form-label">Lapso</label>
      <div class="col-sm-10">
        <select class="form-control" name="lapso">
          <option value="00:20">20 minutos</option>
          <option value="00:30">30 minutos</option>
          <option value="00:40">40 minutos</option>
          <option value="00:50">50 minutos</option>
          <option value="01:00">1 hora</option>
        </select>
      </div>
    </div>
    <div class="form-group row">
      <div style="padding-left: 38%;" class="offset-sm-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Generar</button>
        <%= link_to "Ver horarios registrados", horarios_path, :class => "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/estilistas/citaspest.html.erb
<link rel="stylesheet" type="text/css" href="css/estilistas.css">
<br>
<h1 align="center">Citas</h1><br>
<div align="center">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Cliente</th>
        <th>Teléfono fijo</th>
        <th>Teléfono móvil</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Dirección</th>
        <th>Estado</th>
      </tr>
    </thead>
    <tbody>
      
      <% @citasp.each do |cita| %>
      <%= form_tag '/confirmarcita' do %>
      <tr>
        <th scope="row"><%= Person.find_by(id: (Customer.find_by(id: cita.customer_id).person_id)).nombre%> 
        <%= Person.find_by(id: (Customer.find_by(id: cita.customer_id).person_id)).apellido%></th>
        <td><%= Person.find_by(id: (Customer.find_by(id: cita.customer_id).person_id)).telefono_fijo%></td>
        <td><%= Person.find_by(id: (Customer.find_by(id: cita.customer_id).person_id)).telefono_movil%></td>
        <td><%= cita.fecha%></td>
        <td><%= x = '%02d' % (cita.hora_inicio.hour) %>:<%= x = '%02d' % (cita.hora_inicio.min) %></td>
        <td><%= Ubication.find_by(id: (Person.find_by(id: (Customer.find_by(id: cita.customer_id).person_id)).ubication_id)).direccion%></td>
        <td> <button name="confirmar" value="1" type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button></td>
        <td> <button name="cancelar" value="2" type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span></button></td>
        <input type="hidden" name="id"  value="<%= cita.id%>">
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table><br>

</div>

app/views/estilistas/cortesest.html.erb
<link rel="stylesheet" type="text/css" href="css/estilistas.css">
<br><h1 align="center">Cortes</h1><br>


<div align="center">
  <div class="container">
    <div class="row">
      <% @cortes.each do |corte| %>
      
      <div class="col-sm-4">

        <div><a target="_blank"><img class="imagen1" src="<%= corte.foto %>"></a></div>
        <br>
        <b>Nombre:</b>  <%=  corte.nombre_corte %>
        <br>
        <b>Descripción:</b> <%= (corte.descripcion).slice(0,15) + "..." %>
        <br>
        <br>
        <input type="hidden" name="id"  value="<%= corte.id%>">
        <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#leerMas<%= corte.id%>">Leer más</button><br><br>
      </div>
      <% end %>
    </div>
  </div>
</div>




<br><div style="padding-left: 44%;" class="boton">
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#agregarCorte">Agregar corte</button></div>

<!-- Modal Leer más -->

<% @cut.each do |corte| %>
<div class="modal fade" id="leerMas<%= corte.id%>" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Corte</h4>
      </div>
      <div class="modal-body">
       <div><a target="_blank"><img class="imagen1" src="<%= corte.foto %>"></a></div>
       <br>
       <b>Nombre:  </b>   <%=  corte.nombre_corte %>
       
       <br>
       <b>Descripción:</b> <%= corte.descripcion%>
       <br>
       <br>
     </div>
     <div class="modal-footer">
      <button type="button" class="btn btn-primary" data-dismiss="modal" >Cerrar</button>
    </div>
  </div>
</div>
</div>
<% end %>



<!-- Modal Agregar corte -->
<div class="modal fade" id="agregarCorte" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Agregar corte</h4>
      </div>
      
      <%= render "cut" %>
      
    </div>
  </div>
</div>

app/views/estilistas/crearcita.html.erb
aaa

app/views/estilistas/horarios.html.erb
<link rel="stylesheet" type="text/css" href="css/estilistas.css">
<br><h1 align="center">Horarios registrados</h1>
<br>
<% @schedules.each do |schedule| %>
<div align="center">
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title"><small>Horario registrado </small><span class="pull-right"></span></span></h3></div>
		<div class="panel-body">
			El día <%= schedule.fecha %> tiene disponibilidad a las <%= x = '%02d' % (schedule.hora_inicio.hour) %>:<%= x = '%02d' % (schedule.hora_inicio.min) %>
		</div>
	</div>

</div>
<% end %>

app/views/estilistas/mainest.html.erb
<link rel="stylesheet" type="text/css" href="../css/mainest.css">
<br>
<h1 align="center">¡Bienvenid@ <%= @nombre%>!</h1>
<div class="notifications">
  <div class="toggle"></div>
  <div class="messages">
  	<% @citassol.each do |cita| %>
    <a href="/citaspest" class="message">Tiene una solicitud de cita el día <%= cita.fecha%></a>
  </div>
</div>
<% end %>


<!-- <script class="cssdeck" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script>
$(function() {
  $(".notifications .messages").hide();
  $(".notifications").click(function() {
    if ($(this).children(".messages").children().length > 0) {
</script> -->

app/views/estilistas/perfilest.html.erb
<!-- <script src="bower_components/es6-promise/es6-promise.auto.min.js"></script>
<script src="bower_components/sweetalert2/dist/sweetalert2.min.js"></script>
<script src="scripts/alertas.js"></script> -->
<script type="text/javascript" src="scripts/voz.js"></script>
        <style>
                .container{
                        width: 70%;
                        text-align: left;
                }
                .alinear{
                        text-align:center;
                        margin:auto;
                }
        </style>
<br>
<h1 align="center">Perfil</h1>

<% if flash[:notice] %>
<br><br>
<container align="center">
<div class="alert alert-success alert-dismissable" >

        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <strong><%= flash[:notice] %> </strong>
</div>
</container>
<br><br>
<% end %>

<%= render "perfilform" %>

app/views/estilistas/verexpest.html.erb
<link rel="stylesheet" type="text/css" href="css/estilistas.css">
<br><h1 align="center">Experiencias</h1><br>

<div align="center">
  <div class="container">
    <div class="row">
      <% @experiencias.each do |experiencia| %>
      <div class="col-sm-4">
        <div><a target="_blank"><img class="imagen1" src="<%=experiencia.foto_exp%>"></a></div>
        <br>
        <b>Fecha:</b>
        <%= Time.at(experiencia.created_at).to_date %>
        <br>
        <br>
        <b>Autor:</b>
        <%=Person.find_by(id: experiencia.person_id).nombre %>
        <br>
        <br>
        <b>Relato:</b>
        <%= (experiencia.comentario).slice(0,15) + "..." %>
        <br>
        <br>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#leerMas<%= experiencia.id%>">Leer más</button><br><br>
      </div>
      <% end %>
    </div>
  </div>
</div>

<br><div style="padding-left: 45%;" class="boton">
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Nueva experiencia</button></div>

<!-- Modal Nueva experiencia -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Nueva experiencia</h4>
      </div>
      <%= render "expe" %>
  </div>
</div>
</div>

<!-- Modal Leer más -->
<% @experienciasm.each do |experiencia| %>
<div class="modal fade" id="leerMas<%= experiencia.id%>" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Experiencia</h4>
      </div>
      <div class="modal-body">
       <div><a target="_blank"><img class="imgmodal" src="<%=experiencia.foto_exp%>"></a></div>
       <br>
       <b>Fecha:</b>
       <%= Time.at(experiencia.created_at).to_date %>
       <br>
       <br>
       <b>Autor:</b>
       <%=Person.find_by(id: experiencia.person_id).nombre %>
       <br>
       <br>
       <b>Relato:</b>
       <%= experiencia.comentario %>
       <br>
       <br>
     </div>
     <div class="modal-footer">
      <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
    </div>
  </div>

</div>
</div>
<% end %>